### ISSUE TITLE
Won't Connect

### ISSUE THREAD

**Issue by JhettHeliks** [maxchehab/remote-linux-unlocker#1]
App saying "Invalid IP address" and Terminal stuck on "Processing Request"
Also when you say "Make sure your computer is in pairing mode" do you mean bluetooth?
Does this still work or is it broken?

**Comment by ckrmml** [comment]
Also trying to get this work but with cinnamon and python3, so i have to rewrite parts (like all the prints), anyways, pairing seems to be working over wlan, hadn't activated it on my smartphone and got the same `Invalid IP address` error you get. 
What i did:

```
git clone https://github.com/maxchehab/Remote-Linux-Unlocker  

cd /dir/repo/was/cloned/to/linux-daemon  

# edit the unlocker-daemon.py to reflect correct path
nano unlocker-daemon.py

# i just copied the daemon.service AFTER renaming it from 'deamon' to 'daemon'
sudo cp unlocker-daemon.service /etc/systemd/system/unlocker-daemon.service

# did this without the 'sudo' since i was still authorized
sudo systemctl daemon-reload
sudo systemctl enable unlocker-daemon
sudo systemctl start unlocker-daemon

# rename 'remote-linux-pair' to 'remote-linux-pair.py' cause it did not work 
python remote-linux-pair.py
```
have wlan activated on smartphone, start the app and then i get the following error
```
[chris@tp-w520 linux-daemon]$ python remote-linux-pair.py 
You are about to pair a new device to this computer.
If you have not done so already, please open the Remote Linux Unlocker app.
You can download it here: https://play.google.com/store/apps/details?id=com.maxchehab.remotelinuxunlocker
When you are ready, please type the following IP address into the required field on your device.

IP Address: 192.168.0.100

Awaiting your response...
Connection received...
Processing request...
Traceback (most recent call last):
  File "remote-linux-pair.py", line 74, in <module>
    connection.sendall('{"status":"success"}')
TypeError: a bytes-like object is required, not 'str'
```
still trying to sort this out, so seems kind of broken, at least for me.

so changing
```
connection.sendall('{"status":"success"}')
``` 
to 
```
connection.sendall(str.encode('{"status":"success"}'))
```
seems to work, pairing is done, if i try to pair my smartphone again it says it is already paired but the app is just blank white after this, so still somethings not working as intended here

**Comment by TheLinuxMan02** [comment]
> Also trying to get this work but with cinnamon and python3, so i have to rewrite parts (like all the prints), anyways, pairing seems to be working over wlan, hadn't activated it on my smartphone and got the same `Invalid IP address` error you get.
> What i did:
> 
> ```
> git clone https://github.com/maxchehab/Remote-Linux-Unlocker  
> 
> cd /dir/repo/was/cloned/to/linux-daemon  
> 
> # edit the unlocker-daemon.py to reflect correct path
> nano unlocker-daemon.py
> 
> # i just copied the daemon.service AFTER renaming it from 'deamon' to 'daemon'
> sudo cp unlocker-daemon.service /etc/systemd/system/unlocker-daemon.service
> 
> # did this without the 'sudo' since i was still authorized
> sudo systemctl daemon-reload
> sudo systemctl enable unlocker-daemon
> sudo systemctl start unlocker-daemon
> 
> # rename 'remote-linux-pair' to 'remote-linux-pair.py' cause it did not work 
> python remote-linux-pair.py
> ```
> 
> have wlan activated on smartphone, start the app and then i get the following error
> 
> ```
> [chris@tp-w520 linux-daemon]$ python remote-linux-pair.py 
> You are about to pair a new device to this computer.
> If you have not done so already, please open the Remote Linux Unlocker app.
> You can download it here: https://play.google.com/store/apps/details?id=com.maxchehab.remotelinuxunlocker
> When you are ready, please type the following IP address into the required field on your device.
> 
> IP Address: 192.168.0.100
> 
> Awaiting your response...
> Connection received...
> Processing request...
> Traceback (most recent call last):
>   File "remote-linux-pair.py", line 74, in <module>
>     connection.sendall('{"status":"success"}')
> TypeError: a bytes-like object is required, not 'str'
> ```
> 
> still trying to sort this out, so seems kind of broken, at least for me.
> 
> so changing
> 
> ```
> connection.sendall('{"status":"success"}')
> ```
> 
> to
> 
> ```
> connection.sendall(str.encode('{"status":"success"}'))
> ```
> 
> seems to work, pairing is done, if i try to pair my smartphone again it says it is already paired but the app is just blank white after this, so still somethings not working as intended here

I'm having that white screen issue as well. I'm thinking it's a compatibility issue with newer versions of Android.
